### PR TITLE
i made a few personal changes, implement what you like, trash the rest.

### PR DESCRIPTION
**Pull request by multinerd**
- removed screenshots because it shared the same view as the screenshots in index.html
  http://imgur.com/iw5eBrm
- relocated  changelog.html from separate folders.
- cleaned up and beautify (added some css elements) index.html and changelog.html
- relocated packages and screenshots folder into depictions folder (keep the root directory a bit cleaner)

use the links below to see the difference 

http://multinerd.github.io/repo/depictions/?p=template

https://cydia.jakes.site/depictions/?p=com.jake0oo0.instamute

### CODE REVIEW

**Comment by multinerd** [comment]
oops, forgot to remove the template images some may be nsfw

**Comment by jengel3** [comment]
Thanks, I'll test the changes ASAP :smile:

**Comment by multinerd** [comment]
so to go over the second pull request, 

---

this applies to index.html and changelog.html
i was using 

$.getJSON("/repo/depictions/packages/" + dPackage + ".json", function(data) {

which resulted in always going to root and looking for a repo folder, this would cause issues if the files were located in /cydiarepo/depictions/...

i changed it to 

$.getJSON("packages/" + dPackage + ".json", function(data) {

so that it only looks for a package folder where html file is located.

---

2nd change, i added a back button from changelog to description. hitting back at the current state would bring me back to search results, installed or changes tab, which was IMO very annoying.

**Comment by jengel3** [comment]
I really like the back button :+1: One of the features that most of the main repos don't have that really bothers me.

Also, it seems that the Javascript doesn't correctly layout the images to be side by side for all rows. That may have been my fault, as I haven't tested it with this many images before.

**Comment by multinerd** [comment]
Yea that's why I had the pictures up to begin with. I'm still learning, so let me know if/how you fixed it so I can take note.

**Comment by jengel3** [comment]
Will get this merged ASAP. Sorry for the delays :smile:

**Comment by multinerd** [comment]
its fine, i took a little break myself. i figured out why the images wont load correctly...

i swapped col-xs-12 and col-xs-6 on lines 123 and 125 while testing and forgot to revert it. derp move on my part, but it woks with 1-16 images (i couldnt imaging a package with more than 16 screenshots)

**Comment by multinerd** [comment]
according to my friends, the dropdown was better than sending me to changelog.html with a semi-hidden back button. i liked the changes and decided to implement them to screenshots as well. take a look

http://multinerd.github.io/repo/depictions/?p=template

**Comment by jengel3** [comment]
Wow, it actually looks really nice on mobile. Will definitely merge this ASAP!

**Comment by multinerd** [comment]
yea theres slight lag with the jquery toggles with screenshots and changelog but its bearable(iphone 5)

for the most part, im pretty happy with the outcome. if you have any ideas to improve it, let me know

**Comment by jengel3** [comment]
All merged :shipit: Will update my example repository with all these changes ASAP.

**Pull request merged**
